language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
before_script:
  - pip install -r requirements.txt

script:
  - python3 -m unittest discover -s tests -p "*_test.py"

after_success:
  - coveralls
